### ISSUE TITLE
expose private functions?

### ISSUE THREAD

**Issue by sintaxi** [expressjs/vhost#16]
Hi there, would you accept a pull request that exposes the private functions in this lib?

**Comment by dougwilson** [comment]
Hi @sintaxi, I'm really sorry I did not see your issue here (apparently I was not subscribed to notifications on this repository). So some of them are just slimmed down versions already available in `npm` modules, and I'd be happy to point around if that's the case.

Which particular functions were you looking to export?

**Comment by dougwilson** [comment]
I hope it's OK, but I'm going to close this issue, since I'm not sure which functions you are looking to export.

**Comment by ttonyh** [comment]
I think the private functions he's talking about are the following:
* hostnameof
* hostregexp
* vhostof

They would be helpful for use in other parts of of an app to predict what "vhost" will be used.

**Comment by WORMSS** [comment]
@dougwilson 
Is there any word on exposing them?

My usecase.. [Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQZTVAN3wBo4YBPMNOPQ-AeTBmAgDsBnOAXzgDMoIIOAHIAFjBhh2wgNwAoUJFiIU6LGgAKAgB7laRKNz4ChYiWAC0YHeVkLw0eBSoqAkq2SDgrAOYBZNHZ2DB9qHn5BEXFJOzkAEzRkABsMdD4AVw9mNjhRCHYYdFDtMAAKAgwkgC44AqhvHzgAHzgAJTQfAFESgEoa9q6S+QTk1OpeTORs1lz8mFYMEDQIXlL0AEca908QBoCgkLQ+2sKG4cSUtM8OeAgmFg4a-QZ7tnZ5OWuClDZeYB8agBtOoNUisdIgABG+AAuoCYXAALxwQFyOAo4RsNAAOgAVHjhKQABwABiJAEYYcQ0RiYAB3CB4gnEskAJipchhHy+8GsEG0wECSJ+rD+PmxIAwZVKgLiggw3lIShgMJ6SIAfIgaTy4EU0CVhXk6h19WU5ZLvD15OidUg6WhIaQ6ZweMjUJhsFp+Xp8AZSkgYKlQjAagADaJgKoAeijSQgyEqRpDABIEMquKHuFaaegYOkoDMEDT0dgCjU1mhNnBtl5fPtgqE1YjNXqStjSzBSkmFksVhX1j0etT0ej7Y7i3BncPuPIuNnPmpsM8oKU7tN2D0adi2KVhBt0oEYIS4P3SOgNxqtSO+NATzq+bo4Cs4A-BRei9f0cBeCeAIQP8h20PftBxFZhwTQa1P1zfMZgA7Ex1PXVAmza8uAnc9sQKLB0nYABhCAEmFAAWEliKg9FMLQVg4lKVCsy3HdhHSMAfCgDAEmPJD2HjABrNAYFIURMDiJtNQ-EdeFvUp7xsJ8f1fFCr0-b8-3gjsQLVa5wIPCiRxggsXxsBD2G4viBKEkT6PRdDrx45B+JgbEEjqCByDoqC5y3JJgAKajSmI4iAGZsyAA)

```ts
  .on('upgrade', (req, socket, head) => {
    for (const proxy of proxies) {
      if (!proxy.test(req)) continue;
      return proxy.ws(req, socket, head);
    }
    socket.destroy();
  })
```
