### ISSUE TITLE
vhost for multiple domain

### ISSUE THREAD

**Issue by hdriqi** [expressjs/vhost#24]
For example I have 3 domains called abc.com, def.com and ghi.com

I want the vhost to be able to serve *.abc.com, *.def.com and *.ghi.com, but I want to do it automatically means that the domains can be added dynamically. 

Is there any way to do it?

**Comment by hdriqi** [comment]
It turns out that I can use this:

```
const domain = ['abc.com', 'def.com']
domain.forEach((dom)=>{
	mainApp.use(vhost('*.' + dom, myapp))
})
```

Is this a good solution?

**Comment by dougwilson** [comment]
Hi @hdriqi yep, just use the middleware as many times as needed :) 👍
