### ISSUE TITLE
Issues with SEO

### ISSUE THREAD

**Issue by Cool-Programmer** [expressjs/vhost#28]
Hello. 
Although i think my question may sound stupid to you, but i don't know what to do.
I've been using this module with the project i was working on (a month ago), currently it's live. Actually there is no issue with your module, but i got a complaint saying that website absolutely is not getting indexed, and that company's seo experts are not finding any issues in search console and so on. I just thought - can it be because of this? I mean the master website - domain.com is indexed (partly), and some images of the subdomains of it (created with this package) got some of the images indexed (although the website address in google is not https://sub.domain.com, it's https://domain.com), but other then that nothing else seems to be indexed.

Just want to make sure - can it be because of using virtual hosts, or should i look for the problem somewhere else.

**Comment by dougwilson** [comment]
I'm not sure. No one has ever reported that before and I don't have any experience with SEO and no idea what would make something not get indexed by a search engine and something else get indexed.

I use this module on some sites and they appear in Google search results, but they got there magically as I did nothing to get them there.

**Comment by Cool-Programmer** [comment]
@dougwilson When you used this module, have the sub-sites that were running with vhost were indexed as usual? I somehow managed to find a couple of images, but their URL is not the sub.domain.com, they're domain.com which is actually wrong, and that's why i'm thinking that issues are related to this package.

**Comment by dougwilson** [comment]
Yea, everything shows as normal. I really have no idea what would be wrong. What action can I do to move this issue forward?

**Comment by Cool-Programmer** [comment]
I guess you can't help me anyway with this, i'll try to find something by myself.
Anyway, thank you for your help.

**Comment by dougwilson** [comment]
It's no problem. If you determine the issue you're welcome to pull request the fix if it is indeed this module. Without some instructions on how to reproduce the issue I don't really have anything to debug to determine the cause.

**Comment by Cool-Programmer** [comment]
Thank you very much.
Surely, i'll post an update or create a pull request if i'll be lucky enough to find something.
Thanks
