### ISSUE TITLE
HTTPS Server

### ISSUE THREAD

**Issue by dutchvanderlinde** [expressjs/vhost#35]
Hiya, I was looking around in the issues and I saw #23. I wanted to add, is there a way we can have a different certificate for certain domains? I was looking into the vhttps module but it appears it doesn't support the "ca" object field for the SSL, as it's not working correctly for me. I'd love some sort of support for this module natively. Thanks!

*Basically vhttps doesnt have an option to send the correct Intermediate Certificates, therefore its saying the connection isn't secure as it cannot verify issuer.*

**Comment by dougwilson** [comment]
This module only comes into play after certificates have been exchanged. This is handled by Node.js itself. You should open an issue in the Node.js issue tracker.
