### ISSUE TITLE
Unable to serve root domain and 1 subdomain

### ISSUE THREAD

**Issue by Zophiel** [expressjs/vhost#37]
I am unbale to setup my vhosts correctly.

I have 1 root domain and 1 subdomain I want to facilitate.
Root domain is hosted in a public directory.
Analytics subdomain is hosting in an analytics directory.

Both apps have an index.html
```js
if (process.env.NODE_ENV !== 'production') {
    // DEV
    app.use(vhost('politie.localhost.com', dataApp));
    app.use(vhost('localhost.com', mainapp));
    app.use(vhost('www.localhost.com', mainapp));
  } else {
    // LIVE
    app.use(vhost('analytics.un-innovation.tools', dataApp));
    app.use(vhost('un-innovation.tools', mainapp));
    app.use(vhost('www.un-innovation.tools', mainapp));
  }
```

This is causing content security errors on the live domain.

> Refused to load the font 'data:font/woff;base64,...' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by dougwilson** [comment]
Hi @Zophiel , sorry you're having issues. I don't think there is anything that this module can do to fix it--it sounds like you need to set up CORS on the client side for cross-domain communications.
