### ISSUE TITLE
Vhost + ExpressJS + NextJS

### ISSUE THREAD

**Issue by phibersoft** [expressjs/vhost#41]
I have a two application like this architecture : 

I cannot export apps (Because of "app.prepare()" line). How can I integrate with vhost?
```js
const express = require('express');
const next = require('next');

const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });
const handle = app.getRequestHandler();

app.prepare()
	.then(() => {
		const server = express();

		server.get('/api', (req, res) => {
			// TODO
			console.log('Hello! Do you want to use the API?');
			res.send('kursinfo');
		});
		server.get('*', (req, res) => {
			return handle(req, res);
		});

		const port = process.env.PORT;
		server.listen(port, err => {
			if (err) throw err;
			console.log('> Ready on http://localhost:' + port);
		});
	})
	.catch(ex => {
		console.error(ex.stack);
		process.exit(1);
	});
```

**Comment by dougwilson** [comment]
This module is a middleware. In the above code, you would use this within your promise chain, with `server.use` calls.

**Comment by micheleriva** [comment]
@phibersoft I had a similar problem, and I believe `vhost` is not the right solution for Next.js, as it is a middleware for Express.js (as @dougwilson was saying).

I solved the problem by creating a different middleware that allows you to host a single Next.js app in multi-tenancy mode: https://github.com/micheleriva/krabs which

Feel free to reach out on that repo if you need some help 🙂
