### ISSUE TITLE
Making a TCP Webserver public with vhost

### ISSUE THREAD

**Issue by spiderlord202** [expressjs/vhost#44]
I am using the in-built NET module automatically installed with the node.js engine to make a tcp server for multiple reasons and I am unsure if I can publish it with local tunnel some way and if possible attach a public port to. I need to do this because I am trying to host a Postgres server and I need to specify a host + port (optional?)

**Comment by dougwilson** [comment]
Hi @spiderlord202 this module is just for use with the in-built HTTP module or with the Express framework. As such, I think it would fall outside of the use-case you are looking for.
