### ISSUE TITLE
Trailing slashes in "hostname" argument cause issues

### ISSUE THREAD

**Issue by bitshiftnetau** [expressjs/vhost#47]
Having a trailing slash on the `hostname` argument is causing the the argument to appear false when passed into `vhost` and is thus discarded. 

See **[https://stackoverflow.com/questions/68662812/argument-hostname-required-vhost/68663081#68663081](url)**

Error from that link:

```
TypeError: argument hostname is required
    at vhost (/var/app/current/node_modules/vhost/index.js:39:11)
    at Object.<anonymous> (/var/app/current/app.js:554:9)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
/var/app/current/node_modules/vhost/index.js:39
    throw new TypeError('argument hostname is required')
    ^
```

Broken code from that link: 
```

const app = express();
const register_app = express();
const nonadmin_app = express();
    register_app.use(express.static(path.resolve(__dirname, './build/register')));
nonadmin_app.use(express.static(path.resolve(__dirname, './build/nonadmin')));    

app.use(vhost('register.<eb-dev-url>.elasticbeanstalk.com/', register_app))
app.use(vhost('nonadmin.<eb-dev-url>.elasticbeanstalk.com/', nonadmin_app))
app.use(vhost('api.<eb-dev-url>.elasticbeanstalk.com/', api))

register_app.get('/register', (req, res) => {
    res.sendFile(path.resolve(__dirname, './build/register', 'index.html'));
})

nonadmin_app.get('/nonadmin', (req, res) => {
    res.sendFile(path.resolve(__dirname, './build/nonadmin', 'index.html'));
})
```

Removing the trailing slash at `....elasticbeanstalk.com/` and changing to `....elasticbeanstalk.com` fixed the issue. This shouldn't really be a problem and I can see inside `vhost` there is already some regex happening so might be worth just adding that character for completeness sake. I suck at regex so unfortunately I cannot submit a PR on this one.

**Comment by dougwilson** [comment]
The code you provided does not raise the error given. In fact, it generates no error at all and creates a middleware to match the hostname you provided.

If having a string end with a slash makes Javascript think the string is not there, that is some kind of critical Javascript issue; the module cannot do something with that argument if it is blank in the module's arguments.

**Comment by bitshiftnetau** [comment]
I don't know what to tell you man... I removed the trailing slash and it
worked on AWS. Put it back and had the issue again.

**Comment by dougwilson** [comment]
I'm not saying I don't believe you, just stating what can be done: if adding the slash makes `hostname` argument false to this module, then there is no way thia module can remove the trailing slash from the string, as it never got the string.

**Comment by bitshiftnetau** [comment]
Yeh sorry I'm misreading what you're saying. Ok cool, I guess I'll need to investigate more and raise the bug in the right spot.
